import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/layout/providers";

const inter = Inter({
  subsets: ['greek'],
  // weight: ['400'], // Adjust the weights according to your usage
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
        >
          <div className="fixed w-full h-full bg-white dark:bg-black duration-300 overflow-auto">
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
