import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/layout/providers";

const inter = Inter({
  subsets: ['greek'],
  // weight: ['400'], // Adjust the weights according to your usage
});

export const metadata = {
  title: "MD. Maruf Hossain",
  description: "Generated by next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
